### ISSUE TITLE
neon performance number question on Android+Nexus-Player

### ISSUE THREAD

**Issue by ggfan** [intel/ARM_NEON_2_x86_SSE#7]
with this sample 
    https://github.com/googlesamples/android-ndk/tree/master/hello-neon
when executing on nexus Player, the performance is half of c version( actually slower); while on ARM7 it boost the performance number by 2x. Is there something obviously wrong?

**Comment by caand** [comment]
Hi Gerry,

 

That is a very bad example. It's using 64-bit registers which are not translated efficiently to SSE.

Also the loop is very simple and short – you can have limitations in actual looping and/or memory access time.

 

Regards,

Calin Andrian

**Comment by Zvictoria** [comment]
HI, Gerry. Thanks for asking. While the answer from Calin below is true indeed, there may be another reason. Could you please check if compiler auto vectrorization is on when compiling pure C version? If it is (and I assume it is) then you comparison is not fair because for the simple cases the compiler generated code may be faster. It is also worth looking at your compiler options for ARM_NEON_2_x86_SSE compilation. Probably they are not optimal enough.
And again – Calin’s answer is more than valid there

regards

Victoria

**Comment by ggfan** [comment]
thank you for your quick response! what are the suggested ways ( register size for example ) for ATOM + NEON?  this sample has been inside NDK for a while, developers mainly wants to know how to compile things with NDK toolchain, it fulfill its purpose. However it might make a point to show developers that neon really buys some performance ( otherwise why bother ?). Hence I think it make some sense to look at the performance numbers for both arm and x86.

I think I realized that @caad has been sending questions about the neon for NDK. if you could send me more detailed info about how to improve this sample to show x86 is matching the performance on C front(probably better, matching ARM's neon), I would like to get it improved. I also understand this would be extra burden on you guys since you do not support it anymore, but some info might help.

**Comment by ggfan** [comment]
Oops, accidentally closed it

**Comment by Zvictoria** [comment]
Hi, ggfan. Let me explain it again: "the pure C performance" you are referring to looks like SSE one (created under the hood by compiler).  Is it absolute value worse than for ARM NEON one?
While **optimization of any piece of code using NEON  to work better on SSE  is totally outside of this tool scope**, you may look at compile time warnings about serial execution slowdown .  If any of such instructions are  present you may change the code to avoid them.

**Comment by caand** [comment]
Thanks, Victoria - we think the same. This is not a magic tool, you have to
look under the hood sometimes. But it's very useful - I use it extensively,
with very little SSE specific code when needed.
Gerry, the example is really against SSE philosophy. It reads 64-bit chunks
(advised against in SSE). It uses NEON long (16-to-32) multiply-accumulate
(no direct or even decent equivalent in SSE). Just look at the code to
emulate the long mul, without accumulate (vmull_s16):
 #ifdef USE_SSE4
        __m128i a16, b16;
        a16 = _MM_CVTEPI16_EPI32 (_pM128i(a)); // SSE 4.1
        b16 = _MM_CVTEPI16_EPI32 (_pM128i(b)); // SSE 4.1
        return _MM_MULLO_EPI32 (a16, b16); // SSE 4.1
#else
        __m128i low, hi, a128,b128;
        a128 = _pM128i(a);
        b128 = _pM128i(b);
        low =  _mm_mullo_epi16(a128,b128);
        hi =   _mm_mulhi_epi16(a128,b128);
        return _mm_unpacklo_epi16(low,hi);
#endif
On the other hand, long multiply exists in scalar x86 and, with the
probable double-issue CPU, will run very fast.
As long as the inputs are shorts and the arithmetics are on ints, this is
not going to work well. An example with same type for inputs and arithmetic
(float?) will give good results.
Pay attention also how you compile the example for arm without neon. If you
use thumb you'll miss the long multiply-accumulate opcode and the toolchain
default optimization is -Os instead of -O2 (quite oddly).

By the way (Victoria), my preferred way to load shorts without SSE4 is
(written in neon/sse mixed slang):
GCC_INLINE int32x4_t get4shorts(short *in) {
    int16x8_t ii = _mm_loadl_epi64((void *) (in));
    return _mm_srai_epi32(_mm_unpacklo_epi16(ii, ii), 16);
}
Best regards, Calin Andrian

**Comment by ggfan** [comment]
thank you for your help, I will hack on it later: will also take your input and update readme to reflect the fact.
