### ISSUE TITLE
vs 2022 compiler error

### ISSUE THREAD

**Issue by suitmyself** [intel/ARM_NEON_2_x86_SSE#77]
when I include NEON_2_SSE.h with latest visual studio (17.12.1) and compiled with following codes:

```
float32x4_t SSD_vec = vdupq_n_f32(0.0f);
float32x2_t SSD_PSUM = vadd_f32(vget_low_f32(SSD_vec), vget_high_f32(SSD_vec));
SSD = vget_lane_f32(SSD_PSUM, 0) + vget_lane_f32(SSD_PSUM, 1);
```
I get  error:
![image](https://github.com/user-attachments/assets/4c14aebf-0661-4e5c-a185-015ed843e44d)
![image](https://github.com/user-attachments/assets/614c70a3-2a5f-4371-826a-8d658dea3ef2)

but if I  define macro NEON2SSE_DISABLE_PERFORMANCE_WARNING, no error report.

is this a bug of neon_2_sse or latest visual studio ? how to resolve it ? can only by disable warning ?

**Comment by suitmyself** [comment]
debug mode is ok, but release mode report this error

**Comment by Zvictoria** [comment]
Checked it, the problem is - by default in release build VS sets /sdl compilation option that besides some checks treats warnings as errors. So you need just remove this option

**Comment by nburrus** [comment]
Got the same issue, and I think that the problem is not with the warnings, but with _NEON2SSE_64BIT , which gets enabled when the warnings are enabled as well. Independently setting that variable gives the same ICE even with NEON2SSE_DISABLE_PERFORMANCE_WARNING.

Not sure if it was intentional, but the related code is this, so _NEON2SSE_64BIT is linked to the warning.
#   if (defined(_MSC_VER) || defined (__INTEL_COMPILER)) && !defined(NEON2SSE_DISABLE_PERFORMANCE_WARNING)
#       define _NEON2SSE_PERFORMANCE_WARNING(function, EXPLANATION) __declspec(deprecated(EXPLANATION)) function
#       if defined(_M_X64)
#           define _NEON2SSE_64BIT  _M_X64
#       endif
#   else

**Comment by Zvictoria** [comment]
@nburrus thanks a lot for reporting, it looks like a bug to be dealt with
